/**
 * Gemma 4 Agent Skill: Markdown Report Generator
 * Designed for Google AI Edge Gallery / LiteRT-LM workflows.
 * 
 * Takes structured analysis from Gemma and formats it into a clean Markdown document.
 * This can be used by the host app to save a file, display a rendered view, or export to PDF.
 */

export async function execute(parameters) {
  const { title, sections } = parameters;

  try {
    let markdown = `# ${title}\n\n`;
    markdown += `*Generated by Gemma 4 Local Agent*\n`;
    markdown += `---\n\n`;

    if (!Array.isArray(sections) || sections.length === 0) {
      throw new Error("Sections array is required and cannot be empty.");
    }

    sections.forEach(section => {
      markdown += `## ${section.heading}\n`;
      markdown += `${section.content}\n\n`;
    });

    // In a real Android/Edge environment, this might trigger a local file save intent.
    // Here we return the formatted string back to Gemma.
    return JSON.stringify({
      status: "success",
      message: "Report generated successfully.",
      markdown_output: markdown
    });

  } catch (error) {
    return JSON.stringify({
      status: "error",
      message: error.message
    });
  }
}